name: Record H2D/D2H Baselines

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  record:
    uses: google-ml-infra/bap/.github/workflows/run-benchmarks.yaml@fd37d1f65a06f0124d9d2022d97efa8dc8812557 # main
    with:
      registry_file: "tpu_sync/benchmarks/benchmark_registry_record.pbtxt"
      ml_actions_ref: "fd37d1f65a06f0124d9d2022d97efa8dc8812557"
      runner: "linux-x86-n2-32"
